version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "12:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: react-scripts
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: "@material-ui/styles"
    versions:
    - 4.11.3
  - dependency-name: "@material-ui/core"
    versions:
    - 4.11.3
  - dependency-name: eslint-plugin-prettier
    versions:
    - 3.3.1
  - dependency-name: jest-canvas-mock
    versions:
    - 2.3.0
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: elliptic
    versions:
    - 6.5.3
